# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3 as sql

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(827, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 311, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 221, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 181, 41))
        self.label_3.setObjectName("label_3")
        self.harc_kategori = QtWidgets.QComboBox(self.centralwidget)
        self.harc_kategori.setGeometry(QtCore.QRect(240, 60, 201, 61))
        self.harc_kategori.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.harc_kategori.setObjectName("harc_kategori")
        self.harc_kategori.addItem("")
        self.harc_kategori.addItem("")
        self.harc_kategori.addItem("")
        self.btn_ekle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ekle.setGeometry(QtCore.QRect(450, 90, 181, 71))
        self.btn_ekle.setObjectName("btn_ekle")
        self.harc_miktar = QtWidgets.QLineEdit(self.centralwidget)
        self.harc_miktar.setGeometry(QtCore.QRect(240, 130, 201, 21))
        self.harc_miktar.setInputMask("")
        self.harc_miktar.setText("")
        self.harc_miktar.setMaxLength(32767)
        self.harc_miktar.setDragEnabled(True)
        self.harc_miktar.setClearButtonEnabled(True)
        self.harc_miktar.setObjectName("harc_miktar")
        self.wid_Database = QtWidgets.QTableView(self.centralwidget)
        self.wid_Database.setGeometry(QtCore.QRect(20, 170, 791, 371))
        self.wid_Database.setObjectName("wid_Database")
        self.btn_ekle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ekle_2.setGeometry(QtCore.QRect(640, 90, 181, 71))
        self.btn_ekle_2.setObjectName("btn_ekle_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 827, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">Harcamalar Listesi : </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Harcama Kategorisi : </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Harcama Miktarı : </span></p></body></html>"))
        self.harc_kategori.setItemText(0, _translate("MainWindow", "Seçiniz"))
        self.harc_kategori.setItemText(1, _translate("MainWindow", "Ortak Ev Harcaması"))
        self.harc_kategori.setItemText(2, _translate("MainWindow", "Ek Masraf"))
        self.btn_ekle.setText(_translate("MainWindow", "Ekle"))
        self.btn_ekle_2.setText(_translate("MainWindow", "Sıfırla"))