# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from anasayfa_1 import Ui_MainWindow
import sqlite3 as sql
import runpy


class Ui_LoginWindow(object):

    def yeniac(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def loginkapat(self):
        MainWindow.hide()


    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 191, 31))
        self.label.setObjectName("label")
        self.kullaniciadi = QtWidgets.QLineEdit(self.centralwidget)
        self.kullaniciadi.setGeometry(QtCore.QRect(20, 150, 221, 31))
        self.kullaniciadi.setObjectName("kullaniciadi")
        self.girisbutton = QtWidgets.QPushButton(self.centralwidget)
        self.girisbutton.setGeometry(QtCore.QRect(20, 290, 201, 51))
        self.girisbutton.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.girisbutton.setObjectName("girisbutton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.label_3.setObjectName("label_3")
        self.sifre = QtWidgets.QLineEdit(self.centralwidget)
        self.sifre.setGeometry(QtCore.QRect(20, 230, 221, 31))
        self.sifre.setObjectName("sifre")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 191, 31))
        self.label_2.setObjectName("label_2")
        self.sifrebutton = QtWidgets.QPushButton(self.centralwidget)
        self.sifrebutton.setGeometry(QtCore.QRect(30, 530, 201, 51))
        self.sifrebutton.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.sifrebutton.setObjectName("sifrebutton")
        self.uyelikbutton = QtWidgets.QPushButton(self.centralwidget)
        self.uyelikbutton.setGeometry(QtCore.QRect(240, 530, 201, 51))
        self.uyelikbutton.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.uyelikbutton.setObjectName("uyelikbutton")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 24))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def dataac(self):
        runpy.run_module("data")

    def bilgicheck(self):

        if (self.kullaniciadi.text() =="kaangenis" and self.sifre.text() =="12345678") or (self.kullaniciadi.text() == "ramazanduran" and self.sifre.text() == "31canavari"):
            print("basarili")
            self.yeniac()
            self.loginkapat()

        else:
            print("basarisiz")

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Kullanıcı Adı :</span></p></body></html>"))
        self.girisbutton.setText(_translate("LoginWindow", "Giriş"))
        self.label_3.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">Parahane</span></p></body></html>"))
        self.label_2.setText(_translate("LoginWindow", "<html><head/><body><p><span style=\" font-size:24pt;\">Şifre : </span></p></body></html>"))
        self.sifrebutton.setText(_translate("LoginWindow", "Şifremi Unuttum"))
        self.uyelikbutton.setText(_translate("LoginWindow", "Yeni Üyelik"))

        self.girisbutton.clicked.connect(self.bilgicheck)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


