# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hesapui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 444)
        MainWindow.setStyleSheet("background-color: rgb(58, 58, 58);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(10, 320, 61, 71))
        self.btn_1.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(80, 320, 61, 71))
        self.btn_2.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(150, 320, 61, 71))
        self.btn_3.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_3.setObjectName("btn_3")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(150, 240, 61, 71))
        self.btn_6.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(80, 240, 61, 71))
        self.btn_5.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_5.setObjectName("btn_5")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(10, 240, 61, 71))
        self.btn_4.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_4.setObjectName("btn_4")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(10, 160, 61, 71))
        self.btn_7.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(80, 160, 61, 71))
        self.btn_8.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(150, 160, 61, 71))
        self.btn_9.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_9.setObjectName("btn_9")
        self.btn_0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_0.setGeometry(QtCore.QRect(220, 320, 111, 71))
        self.btn_0.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);")
        self.btn_0.setObjectName("btn_0")
        self.btn_sil = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sil.setGeometry(QtCore.QRect(10, 10, 61, 111))
        self.btn_sil.setStyleSheet("text-decoration: underline;\n"
"font: 20pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 82, 167);")
        self.btn_sil.setObjectName("btn_sil")
        self.btn_topla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_topla.setGeometry(QtCore.QRect(220, 240, 51, 71))
        self.btn_topla.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(72, 82, 167);")
        self.btn_topla.setObjectName("btn_topla")
        self.btn_bolme = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bolme.setGeometry(QtCore.QRect(280, 160, 51, 71))
        self.btn_bolme.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(72, 82, 167);")
        self.btn_bolme.setObjectName("btn_bolme")
        self.btn_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikar.setGeometry(QtCore.QRect(280, 240, 51, 71))
        self.btn_cikar.setStyleSheet("font: 30pt \"Nirmala UI\";\n"
"background-color: rgb(72, 82, 167);")
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carp.setGeometry(QtCore.QRect(220, 160, 51, 71))
        self.btn_carp.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(72, 82, 167);")
        self.btn_carp.setObjectName("btn_carp")
        self.sonuc = QtWidgets.QLineEdit(self.centralwidget)
        self.sonuc.setGeometry(QtCore.QRect(80, 10, 251, 111))
        self.sonuc.setStyleSheet("font: 20pt \"Nirmala UI\";\n"
"background-color: rgb(141, 141, 141);\n"
"")
        self.sonuc.setObjectName("sonuc")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 334, 21))
        self.menubar.setObjectName("menubar")
        self.menuHESAPLA = QtWidgets.QMenu(self.menubar)
        self.menuHESAPLA.setObjectName("menuHESAPLA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHESAPLA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_sil.setText(_translate("MainWindow", "<"))
        self.btn_topla.setText(_translate("MainWindow", "+"))
        self.btn_bolme.setText(_translate("MainWindow", "%"))
        self.btn_cikar.setText(_translate("MainWindow", "-"))
        self.btn_carp.setText(_translate("MainWindow", "x"))
        self.menuHESAPLA.setTitle(_translate("MainWindow", "HESAPLA"))
