# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 620)
        MainWindow.setStyleSheet("background-color: rgb(128, 137, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.boy = QtWidgets.QSpinBox(self.centralwidget)
        self.boy.setGeometry(QtCore.QRect(80, 70, 191, 41))
        self.boy.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 157, 144);")
        self.boy.setMaximum(1000)
        self.boy.setObjectName("boy")
        self.en = QtWidgets.QSpinBox(self.centralwidget)
        self.en.setGeometry(QtCore.QRect(80, 10, 191, 41))
        self.en.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 157, 144);")
        self.en.setMaximum(1000)
        self.en.setObjectName("en")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 61, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 52, 25))
        self.label_2.setObjectName("label_2")
        self.btn_H_Alan = QtWidgets.QPushButton(self.centralwidget)
        self.btn_H_Alan.setGeometry(QtCore.QRect(290, 70, 261, 41))
        self.btn_H_Alan.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 167, 44);")
        self.btn_H_Alan.setObjectName("btn_H_Alan")
        self.sonuc_alan = QtWidgets.QLineEdit(self.centralwidget)
        self.sonuc_alan.setGeometry(QtCore.QRect(290, 10, 261, 41))
        self.sonuc_alan.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 242, 137);")
        self.sonuc_alan.setObjectName("sonuc_alan")
        self.btn_Cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cikis.setGeometry(QtCore.QRect(500, 540, 261, 41))
        self.btn_Cikis.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(173, 69, 51);")
        self.btn_Cikis.setObjectName("btn_Cikis")
        self.btn_Sifirla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sifirla.setGeometry(QtCore.QRect(500, 490, 261, 41))
        self.btn_Sifirla.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(247, 255, 83);")
        self.btn_Sifirla.setObjectName("btn_Sifirla")
        self.btn_Hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Hesapla.setGeometry(QtCore.QRect(500, 440, 261, 41))
        self.btn_Hesapla.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(144, 255, 119);")
        self.btn_Hesapla.setObjectName("btn_Hesapla")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 140, 261, 41))
        self.comboBox.setStyleSheet("font: 63 20pt \"Sitka Banner Semibold\" \"MS Shell Dlg 2\";\n"
"background-color: rgb(72, 157, 144);")
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">EN       :</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">BOY:</span></p></body></html>"))
        self.btn_H_Alan.setText(_translate("MainWindow", "ALAN HESAPLA"))
        self.btn_Cikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.btn_Sifirla.setText(_translate("MainWindow", "SIFIRLA"))
        self.btn_Hesapla.setText(_translate("MainWindow", "HESAPLA"))
        self.comboBox.setItemText(0, _translate("MainWindow", "70x100 (0,5mm)"))
