# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 678)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(66, 92, 118), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_nickname = QtWidgets.QLineEdit(self.centralwidget)
        self.line_nickname.setGeometry(QtCore.QRect(90, 90, 361, 41))
        self.line_nickname.setObjectName("line_nickname")
        self.btn_giris = QtWidgets.QPushButton(self.centralwidget)
        self.btn_giris.setGeometry(QtCore.QRect(90, 240, 361, 71))
        self.btn_giris.setObjectName("btn_giris")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 151, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 140, 151, 31))
        self.label_2.setObjectName("label_2")
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(90, 170, 361, 41))
        self.line_password.setObjectName("line_password")
        self.btn_yeniuye = QtWidgets.QPushButton(self.centralwidget)
        self.btn_yeniuye.setGeometry(QtCore.QRect(90, 400, 361, 71))
        self.btn_yeniuye.setObjectName("btn_yeniuye")
        self.btn_sifresifirla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sifresifirla.setGeometry(QtCore.QRect(90, 320, 361, 71))
        self.btn_sifresifirla.setMouseTracking(False)
        self.btn_sifresifirla.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_sifresifirla.setAutoFillBackground(False)
        self.btn_sifresifirla.setObjectName("btn_sifresifirla")
        self.line_check = QtWidgets.QLineEdit(self.centralwidget)
        self.line_check.setGeometry(QtCore.QRect(90, 500, 361, 101))
        self.line_check.setObjectName("line_check")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_giris.setText(_translate("MainWindow", "GİRİŞ"))
        self.label.setText(_translate("MainWindow", "KULLANICI ADI:"))
        self.label_2.setText(_translate("MainWindow", "PAROLA:"))
        self.btn_yeniuye.setText(_translate("MainWindow", "YENİ ÜYELİK"))
        self.btn_sifresifirla.setText(_translate("MainWindow", "ŞİFREMİ UNUTTUM"))
