# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sifre_arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SifreWindow(object):
    def setupUi(self, SifreWindow):
        SifreWindow.setObjectName("SifreWindow")
        SifreWindow.resize(1280, 678)
        self.centralwidget = QtWidgets.QWidget(SifreWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 210, 341, 171))
        self.label.setStyleSheet("font: 48pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        SifreWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SifreWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        SifreWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SifreWindow)
        self.statusbar.setObjectName("statusbar")
        SifreWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SifreWindow)
        QtCore.QMetaObject.connectSlotsByName(SifreWindow)

    def retranslateUi(self, SifreWindow):
        _translate = QtCore.QCoreApplication.translate
        SifreWindow.setWindowTitle(_translate("SifreWindow", "sifrewindow"))
        self.label.setText(_translate("SifreWindow", "DENEME"))
